services:
  - type: web
    name: diggu-api
    env: node
    rootDir: api
    plan: free
    buildCommand: npm install && npx prisma generate && npm run build
    startCommand: npm run start:prod
    healthCheckPath: /api/v1/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: ENABLE_SWAGGER
        value: false
      - key: JWT_EXPIRES_IN
        value: 15m
      - key: UPLOAD_DIR
        value: ./uploads
      - key: MAX_FILE_SIZE
        value: 5242880
      - key: DATABASE_URL
        sync: false
      - key: DIRECT_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: CORS_ORIGIN
        sync: false
      - key: RESEND_API_KEY
        sync: false
      - key: EMAIL_FROM
        sync: false

  - type: web
    name: diggu-web
    env: node
    rootDir: web
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run start -- -H 0.0.0.0 -p $PORT
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_API_URL
        sync: false
